name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ChatBotServer
      run: dotnet restore
    - name: Build
      working-directory: ./ChatBotServer
      run: dotnet build --no-restore 
    - name: Test
      working-directory: ./ChatBotServer
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: ./ChatBotServer/Tests/TestResults/coverage.info 

    - name: Setup SSH Action
      # You may pin to the exact commit or the version.
      # uses: LuisEnMarroquin/setup-ssh-action@c5ee88d5ac08d94a584415bbe934b63646ea18ca
      uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        # SSH key
        SSHKEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        # SSH port
        PORT: 22
        # SSH user
        USER: "vojta"
        

   # - name: Install SSH Key
   #   uses: shimataro/ssh-key-action@v2
   #   with:
    #    key: ${{ secrets.SSH_PRIVATE_KEY }} 
     #   known_hosts: asd
        
        
        
