name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ChatBotServer
      run: dotnet restore
    - name: Build
      working-directory: ./ChatBotServer
      run: dotnet build --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Test
      working-directory: ./ChatBotServer
      run: dotnet test --no-build --verbosity normal
      
    - name: Coverage check
      # You may pin to the exact commit or the version.
      # uses: devmasx/coverage-check-action@4a754f8957c6824e0a0d44bf9168fdbdf47e7e2f
      uses: devmasx/coverage-check-action@v1.2.0
      with: 
        type: lcov
        # Github token for create checks
        token: ${{ secrets.GITHUB_TOKEN }}
        # Minimum coverage
        min_coverage: 20
        # Json with coverage result
        result_path: ./ChatBotServer/Tests/TestResults/coverage.info 
