name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ChatBotServer
      run: dotnet restore
    - name: Build
      working-directory: ./ChatBotServer
      run: dotnet build --no-restore 
    - name: Test
      working-directory: ./ChatBotServer
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish
      working-directory: ./ChatBotServer/ChatBotServer
      run: dotnet publish --configuration Release --output ./../../application -p:RuntimeIdentifier=win-x64 -p:SelfContained=true -p:PublishSingleFile=true -p:UseAppHost=true -P:PublishReadyToRun=false -p:PublishTrimmed=true -p:PublishProtocol=FileSystem
      
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: ./ChatBotServer/Tests/TestResults/coverage.info 
        
    - name: Install go-msi
      run: choco install -y "go-msi"
      
    - name: Build Windows Installer MSI from exe file
      uses: AliceOh/CreateWindowsInstaller@1.0.0
      with:
        exefile: ChatBotServer.exe
        
    - name: Upload MSI for Windows to release page
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "test"
        prerelease: true
        title: "Windows Development Build"
        files: |
          ChatBotServer.exe.msi
          
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: 40.122.30.213
        # FTP user
        user: ""
        # FTP password
        password: ""
      
      
      
        
